### ISSUE TITLE
Meta-Analysis Table

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#1]
- [x] Paper that I'll upload here needs to be added
- [x] Go through "TN" papers and see if it is actually TDN
- [x] add time since fire
- [x] add climate
- [x] add location
- [x] Remove papers if only reported the median value
- [x] Match which burn and unburn within a respective paper
- [x] If paper has both pre fire and unburned compare then go back and decide which one to use
- [x] Make <LOD the LOD? <-we should decide what we want to do for these
- [x] Calc effect size/ mean difference
- [x] Make some pretty figures

**Comment by amyerspigg** [comment]
See above
